Future<Map<String, Object?>> fetchLocationData(int id) async {
  await Future.delayed(const Duration(seconds: 1));

  return locationsList.firstWhere(
    (location) => location['id'] == id,
    orElse: () => {},
  );
}

const locationsList = [
  {
    "id": 10,
    "dateCreated": "2025-10-27T19:52:46.000+01:00",
    "lastUpdated": "2025-11-03T22:49:01.000+01:00",
    "name": "Emilia's Cafe - UBI-5",
    "street": "Carrer de Pallars",
    "streetNo": "108",
    "streetAndNumber": "Carrer de Pallars 108",
    "addressExtra": null,
    "zip": "08018",
    "city": "Barcelona",
    "cellphone": null,
    "fax": null,
    "website": "https://facebook.com",
    "email": null,
    "descriptionShort": null,
    "descriptionLong": null,
    "openingHoursNotes": null,
    "lastSyncStarted": null,
    "country": "ES",
    "lat": 41.3960803,
    "lng": 2.1910997,
    "imprint": null,
    "addressDisplay": true,
    "autoSync": false,
    "skipFacebookPicturesUpdate": false,
    "callTrackingNumbers": [],
    "utms": [],
    "phone": null,
    "openingHours": [
      {"dayOfWeek": 1, "from1": "09:00", "to1": "22:00"},
    ],
    "moreHours": [],
    "specialOpeningHours": [
      {"date": "2025-12-21", "closed": true},
      {
        "date": "2025-12-24",
        "from1": "08:00",
        "to1": "12:00",
        "from2": "15:00",
        "to2": "20:00",
      },
    ],
    "businessId": 1216171,
    "businessName": "Pulled Pork Paradise Testaccount 2",
    "businessSyncable": false,
    "businessCountry": "DE",
    "businessType": "ENTERPRISE",
    "status": "ACTIVE",
    "normalizationStatus": "NORMALIZED",
    "photos": [],
    "emailVerification": "UNVERIFIED",
    "labels": [],
    "keywords": [],
    "brands": [],
    "languages": [],
    "socialProfiles": [],
    "paymentOptions": [],
    "attributes": [],
    "timeZone": "Europe/Madrid",
    "temporarilyClosed": {"temporarilyClosed": false, "reopenDate": null},
  },
  {
    "id": 11,
    "dateCreated": "2025-10-22T23:44:57.000+02:00",
    "lastUpdated": "2025-10-22T23:45:11.000+02:00",
    "name": "Deutsche Niederlassung 1",
    "street": "Musterstraße",
    "streetNo": "10A",
    "streetAndNumber": "Musterstraße 10A",
    "addressExtra": null,
    "zip": "10117",
    "city": "Berlin",
    "cellphone": null,
    "fax": null,
    "website": null,
    "email": null,
    "descriptionShort": null,
    "descriptionLong": null,
    "openingHoursNotes": null,
    "lastSyncStarted": null,
    "country": "DE",
    "lat": null,
    "lng": null,
    "imprint": null,
    "addressDisplay": true,
    "autoSync": false,
    "skipFacebookPicturesUpdate": false,
    "callTrackingNumbers": [],
    "utms": [],
    "phone": null,
    "openingHours": [],
    "moreHours": [],
    "specialOpeningHours": [],
    "businessId": 2274876,
    "businessName": "Listings Automated Business",
    "businessSyncable": false,
    "businessCountry": "US",
    "businessType": "ENTERPRISE",
    "status": "ACTIVE",
    "normalizationStatus": "NORMALIZATION_FAILED",
    "photos": [],
    "emailVerification": "UNVERIFIED",
    "labels": [],
    "keywords": [],
    "brands": [],
    "languages": [],
    "socialProfiles": [],
    "paymentOptions": [],
    "attributes": [
      {
        "externalId": "url_whatsapp",
        "displayName": "WhatsApp",
        "valueType": "URL",
        "valueMetadata": null,
        "groupDisplayName": "Place page URLs",
        "value":
            "https://wa.me/493012345678?text=Hallo%2C%20Das%20ist%20eine%20vorausgef%C3%BCllte%20Nachricht%20f%C3%BCr%20Sie%21",
      },
    ],
    "timeZone": null,
    "temporarilyClosed": {"temporarilyClosed": false, "reopenDate": null},
  },
];
