// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7IQFqy4vSg7UvGCAcmNNVPjKe-kr7J5A',
    appId: '1:155302405249:web:3db0e365af3129f3ead980',
    messagingSenderId: '155302405249',
    projectId: 'aisidekik',
    authDomain: 'aisidekik.firebaseapp.com',
    storageBucket: 'aisidekik.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr5Yh2lRIrpbokziU9T0mXO10VcIsGZug',
    appId: '1:155302405249:android:9f0f1dbe98ef39acead980',
    messagingSenderId: '155302405249',
    projectId: 'aisidekik',
    storageBucket: 'aisidekik.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT9u0Zvp8B1L4MnrvNRlAOF41YNlQ9cMg',
    appId: '1:155302405249:ios:bf22273bf98a291cead980',
    messagingSenderId: '155302405249',
    projectId: 'aisidekik',
    storageBucket: 'aisidekik.firebasestorage.app',
    iosBundleId: 'com.example.sidekik',
  );
}
